"""remove course description

Revision ID: 16c2b0dfcb32
Revises: bac2f627068c
Create Date: 2026-06-10 18:25:14.467507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c2b0dfcb32'
down_revision: Union[str, Sequence[str], None] = 'bac2f627068c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
